import calendar from '../../themes/newyear/assets/calendar.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './ResolutionCharades.css';

export const resolutionCharades = charadesGame(
  {
    id: 'resolution-charades',
    title: { 'en-US': 'Resolution Charades', 'pt-PT': 'Mímica das Resoluções' },
    intro: {
      'en-US':
        "Act out the New Year's resolution on the screen without saying a word, while everyone else shouts their guesses. Every resolution they get earns you points. Stuck? Skip it!",
      'pt-PT':
        'Faz a mímica da resolução de Ano Novo que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada resolução que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: calendar,
    words: {
      'en-US': [
        'Going to the gym',
        'Eating more vegetables',
        'Learning to play the guitar',
        'Reading more books',
        'Going for a run every morning',
        'Learning to dance',
        'Drinking more water',
        'Going to bed early',
        'Cleaning my room',
        'Learning to cook',
        'Doing yoga',
        'Learning a new language',
        'Saving money in a piggy bank',
        'Traveling the world',
        'Learning to swim',
        'Walking the dog every day',
        'Eating less chocolate',
        'Spending less time on the phone',
        'Planting a garden',
        'Learning to juggle',
        'Riding a bike to school',
        'Being on time',
        'Brushing my teeth for two minutes',
        'Learning to ski',
        'Painting a picture',
        'Calling grandma more often',
        'Making my bed every morning',
        'Climbing a mountain',
        'Taking more photos',
        'Learning a magic trick',
        'Being more patient',
        'Helping with the dishes',
        'Writing in a diary',
        'Learning to skateboard',
        'Smiling more',
        'Doing ten push-ups a day',
        'Baking bread',
        'Keeping my desk tidy',
        'Going camping',
        'Singing in a choir',
      ],
      'pt-PT': [
        'Ir ao ginásio',
        'Comer mais legumes',
        'Aprender a tocar guitarra',
        'Ler mais livros',
        'Correr todas as manhãs',
        'Aprender a dançar',
        'Beber mais água',
        'Deitar-me cedo',
        'Arrumar o quarto',
        'Aprender a cozinhar',
        'Fazer ioga',
        'Aprender uma língua nova',
        'Poupar dinheiro no mealheiro',
        'Viajar pelo mundo',
        'Aprender a nadar',
        'Passear o cão todos os dias',
        'Comer menos chocolate',
        'Passar menos tempo ao telemóvel',
        'Fazer uma horta',
        'Aprender a fazer malabarismo',
        'Ir de bicicleta para a escola',
        'Ser pontual',
        'Lavar os dentes durante dois minutos',
        'Aprender a esquiar',
        'Pintar um quadro',
        'Ligar mais vezes à avó',
        'Fazer a cama todas as manhãs',
        'Subir uma montanha',
        'Tirar mais fotografias',
        'Aprender um truque de magia',
        'Ter mais paciência',
        'Ajudar a lavar a loiça',
        'Escrever um diário',
        'Aprender a andar de skate',
        'Sorrir mais',
        'Fazer dez flexões por dia',
        'Fazer pão',
        'Manter a secretária arrumada',
        'Ir acampar',
        'Cantar num coro',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': "Act out New Year's resolutions without speaking while the others guess!",
      'pt-PT': 'Faz a mímica de resoluções de Ano Novo enquanto os outros adivinham!',
    },
    themes: ['newyear'],
    thumbnail,
  },
);
