import pumpkin from '../../themes/halloween/assets/pumpkin.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './MonsterCharades.css';

export const monsterCharades = charadesGame(
  {
    id: 'monster-charades',
    title: { 'en-US': 'Monster Charades', 'pt-PT': 'Mímica de Monstros' },
    intro: {
      'en-US':
        'Act out the spooky word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra assustadora que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: pumpkin,
    words: {
      'en-US': [
        'Vampire',
        'Werewolf',
        'Mummy',
        'Zombie',
        'Ghost',
        'Witch on a broom',
        'Black cat',
        'Skeleton dancing',
        'Frankenstein',
        'Carving a pumpkin',
        'Trick or treat',
        'Haunted house',
        'Spider spinning a web',
        'Bat flying',
        'Stirring a cauldron',
        'Scarecrow',
        'Owl',
        'Eating candy',
        'Casting a spell',
        'Creaky door',
        'Monster under the bed',
        'Jack-o-lantern',
        'Graveyard',
        'Bobbing for apples',
        'Wizard',
        'Pirate',
        'Dragon',
        'Robot',
        'Superhero',
        'Scared of the dark',
        'Full moon',
        'Howling wolf',
        'Mad scientist',
        'Putting on a costume',
        'Magic wand',
        'Crystal ball',
        'Sleeping vampire in a coffin',
        'Ghost train',
        'Spooky story by the fire',
        'Rat running',
      ],
      'pt-PT': [
        'Vampiro',
        'Lobisomem',
        'Múmia',
        'Zombie',
        'Fantasma',
        'Bruxa numa vassoura',
        'Gato preto',
        'Esqueleto a dançar',
        'Frankenstein',
        'Esculpir uma abóbora',
        'Doçura ou travessura',
        'Casa assombrada',
        'Aranha a tecer a teia',
        'Morcego a voar',
        'Mexer o caldeirão',
        'Espantalho',
        'Coruja',
        'Comer guloseimas',
        'Lançar um feitiço',
        'Porta a ranger',
        'Monstro debaixo da cama',
        'Lanterna de abóbora',
        'Cemitério',
        'Apanhar maçãs com a boca',
        'Feiticeiro',
        'Pirata',
        'Dragão',
        'Robô',
        'Super-herói',
        'Medo do escuro',
        'Lua cheia',
        'Lobo a uivar',
        'Cientista louco',
        'Mascarar-se',
        'Varinha mágica',
        'Bola de cristal',
        'Vampiro a dormir no caixão',
        'Comboio fantasma',
        'Contar histórias de terror à lareira',
        'Rato a correr',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out spooky words without speaking while the others guess. Vampires, mummies and more!',
      'pt-PT': 'Faz a mímica de palavras assustadoras enquanto os outros adivinham. Vampiros, múmias e muito mais!',
    },
    themes: ['halloween'],
    thumbnail,
  },
);
