import partyHat from '../../themes/birthday/assets/party-hat.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './PartyCharades.css';

export const partyCharades = charadesGame(
  {
    id: 'party-charades',
    title: { 'en-US': 'Party Charades', 'pt-PT': 'Mímica da Festa' },
    intro: {
      'en-US':
        'Act out the party word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra da festa que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: partyHat,
    words: {
      'en-US': [
        'Blowing out the candles',
        'Making a wish',
        'Pin the tail on the donkey',
        'Musical chairs',
        'Hitting a piñata',
        'Blowing up a balloon',
        'Popping a balloon',
        'Opening a present',
        'Cutting the cake',
        'Singing Happy Birthday',
        'Wearing a party hat',
        'Blowing a party horn',
        'Musical statues',
        'Sack race',
        'Egg and spoon race',
        'Hide and seek',
        'Pass the parcel',
        'Limbo dance',
        'Bouncy castle',
        'Face painting',
        'Magician pulling a rabbit out of a hat',
        'Clown juggling',
        'Wrapping a gift',
        'Writing a birthday card',
        'Eating too much cake',
        'Surprise party',
        'Dancing the conga',
        'Taking a group photo',
        'Lighting the candles',
        'Grabbing sweets from the piñata',
        'Getting the bumps',
        'Treasure hunt',
        'Three-legged race',
        'Pillow fight',
        'Karaoke',
        'Opening a gift you already have',
        'Licking icing off your fingers',
        'Party popper',
        'Falling asleep after the party',
        'Waiting for the guests to arrive',
      ],
      // Portuguese parties have the "parabéns a você" song, the "dança das cadeiras" and the
      // "jogo do lenço" instead of pass the parcel or getting the bumps.
      'pt-PT': [
        'Soprar as velas',
        'Pedir um desejo',
        'Pôr o rabo no burro',
        'Dança das cadeiras',
        'Bater na piñata',
        'Encher um balão',
        'Rebentar um balão',
        'Abrir uma prenda',
        'Cortar o bolo',
        'Cantar os parabéns',
        'Pôr um chapéu de festa',
        'Tocar uma corneta',
        'Estátuas musicais',
        'Corrida de sacos',
        'Corrida da colher e do ovo',
        'Escondidas',
        'Jogo do lenço',
        'Dançar o limbo',
        'Insuflável',
        'Pintura facial',
        'Mágico a tirar um coelho da cartola',
        'Palhaço a fazer malabarismo',
        'Embrulhar uma prenda',
        'Escrever um postal de anos',
        'Comer bolo a mais',
        'Festa surpresa',
        'Dançar em comboio',
        'Tirar uma fotografia de grupo',
        'Acender as velas',
        'Apanhar rebuçados da piñata',
        'Puxar as orelhas ao aniversariante',
        'Caça ao tesouro',
        'Corrida a três pernas',
        'Guerra de almofadas',
        'Karaoke',
        'Abrir uma prenda repetida',
        'Lamber a cobertura dos dedos',
        'Lançar serpentinas',
        'Adormecer depois da festa',
        'Esperar que os convidados cheguem',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out party games and birthday moments without speaking while the others guess!',
      'pt-PT': 'Faz a mímica de jogos de festa e momentos de anos enquanto os outros adivinham!',
    },
    themes: ['birthday'],
    thumbnail,
  },
);
