import egg from '../../themes/easter/assets/egg.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './SpringCharades.css';

export const springCharades = charadesGame(
  {
    id: 'spring-charades',
    title: { 'en-US': 'Spring Charades', 'pt-PT': 'Mímica da Primavera' },
    intro: {
      'en-US':
        'Act out the spring word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra da primavera que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: egg,
    words: {
      'en-US': [
        'Egg hunt',
        'Hopping bunny',
        'Painting an egg',
        'Planting flowers',
        'Chick hatching from an egg',
        'Egg and spoon race',
        'Eating a chocolate egg',
        'Butterfly',
        'Bee buzzing around a flower',
        'Watering the garden',
        'Splashing in a puddle',
        'Opening an umbrella',
        'Flying a kite',
        'Picnic in the park',
        'Lamb jumping in a field',
        'Duck waddling',
        'Frog jumping into a pond',
        'Sneezing from pollen',
        'Rolling an egg down a hill',
        'Carrying a basket of eggs',
        'Spring cleaning',
        'Riding a bike',
        'Picking flowers',
        'Bird building a nest',
        'Caterpillar crawling',
        'Rainbow after the rain',
        'Bunny eating a carrot',
        'Hen sitting on her eggs',
        'Wearing bunny ears',
        'Finding the last hidden egg',
        'Dropping an egg',
        'Mowing the lawn',
        'Hot cross buns',
        'Snail sliding along',
        'Waking up from hibernation',
        'Sunbathing',
        'Hiding the eggs',
        'Blossoming tree',
        'Worm wriggling out of the ground',
        'Eating too much chocolate',
      ],
      // Portuguese Easter brings the folar, sugared almonds and godparents' gifts instead of hot cross buns.
      'pt-PT': [
        'Caça aos ovos',
        'Coelho aos saltos',
        'Pintar um ovo',
        'Plantar flores',
        'Pintainho a sair do ovo',
        'Corrida da colher e do ovo',
        'Comer um ovo de chocolate',
        'Borboleta',
        'Abelha a zumbir à volta de uma flor',
        'Regar o jardim',
        'Saltar para dentro de uma poça',
        'Abrir um guarda-chuva',
        'Lançar um papagaio de papel',
        'Piquenique no parque',
        'Cordeiro aos saltos no campo',
        'Pato a andar',
        'Sapo a saltar para o lago',
        'Espirrar por causa do pólen',
        'Rebolar um ovo pela encosta abaixo',
        'Carregar um cesto de ovos',
        'Limpezas da primavera',
        'Andar de bicicleta',
        'Apanhar flores',
        'Pássaro a fazer o ninho',
        'Lagarta a rastejar',
        'Arco-íris depois da chuva',
        'Coelho a comer uma cenoura',
        'Galinha a chocar os ovos',
        'Pôr orelhas de coelho',
        'Encontrar o último ovo escondido',
        'Deixar cair um ovo',
        'Cortar a relva',
        'Comer folar',
        'Caracol a deslizar',
        'Acordar da hibernação',
        'Apanhar sol',
        'Esconder os ovos',
        'Comer amêndoas',
        'Minhoca a sair da terra',
        'Comer chocolate a mais',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out spring things without speaking while the others guess. Egg hunts, bunnies and more!',
      'pt-PT': 'Faz a mímica de coisas da primavera enquanto os outros adivinham. Caça aos ovos, coelhos e muito mais!',
    },
    themes: ['easter'],
    thumbnail,
  },
);
