import rocket from '../../themes/space/assets/rocket.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './SpaceCharades.css';

export const spaceCharades = charadesGame(
  {
    id: 'space-charades',
    title: { 'en-US': 'Space Charades', 'pt-PT': 'Mímica Espacial' },
    intro: {
      'en-US':
        'Act out the space word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra espacial que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: rocket,
    words: {
      'en-US': [
        'Moonwalk',
        'Rocket launch',
        'Zero gravity',
        'Astronaut putting on a helmet',
        'Alien landing',
        'Looking through a telescope',
        'Shooting star',
        'Planting a flag on the Moon',
        'Spacewalk',
        'Eating space food from a tube',
        'Countdown',
        'Black hole',
        'Robot',
        'UFO beaming someone up',
        'Floating in a spaceship',
        'Meteor shower',
        'Orbiting the Earth',
        'Driving a moon buggy',
        'Laser battle',
        'Making a wish on a star',
        'Sleeping in a space bag',
        'Fixing a satellite',
        'Saturn and its rings',
        'Sunrise from space',
        'Asteroid crash',
        'Martian waving hello',
        'Mission control',
        'Bouncing on the Moon',
        'Docking with the space station',
        'Solar eclipse',
        'Wearing a spacesuit',
        'Comet flying by',
        'Space dog',
        'Star gazing on the grass',
        'Talking over the radio',
        'Splashdown in the ocean',
        'Hyperspace jump',
        'Alien eating a burger',
        'Building a rocket',
        'Waving goodbye to Earth',
      ],
      'pt-PT': [
        'Andar na Lua',
        'Lançamento de um foguetão',
        'Gravidade zero',
        'Astronauta a pôr o capacete',
        'Extraterrestre a aterrar',
        'Olhar por um telescópio',
        'Estrela cadente',
        'Espetar uma bandeira na Lua',
        'Passeio no espaço',
        'Comer comida espacial de um tubo',
        'Contagem decrescente',
        'Buraco negro',
        'Robô',
        'Disco voador a raptar alguém',
        'Flutuar dentro de uma nave',
        'Chuva de meteoros',
        'Andar à volta da Terra',
        'Conduzir um jipe lunar',
        'Batalha de lasers',
        'Pedir um desejo a uma estrela',
        'Dormir num saco-cama espacial',
        'Arranjar um satélite',
        'Saturno e os anéis',
        'Nascer do sol visto do espaço',
        'Choque de um asteroide',
        'Marciano a dizer olá',
        'Controlo da missão',
        'Saltar na Lua',
        'Atracar na estação espacial',
        'Eclipse do sol',
        'Vestir um fato espacial',
        'Cometa a passar',
        'Cão astronauta',
        'Ver as estrelas deitado na relva',
        'Falar pelo rádio',
        'Amarar no oceano',
        'Salto para o hiperespaço',
        'Extraterrestre a comer um hambúrguer',
        'Construir um foguetão',
        'Dizer adeus à Terra',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out space things without speaking while the others guess. Moonwalks, aliens and more!',
      'pt-PT': 'Faz a mímica de coisas do espaço enquanto os outros adivinham. Passeios na Lua, extraterrestres e muito mais!',
    },
    themes: ['space'],
    thumbnail,
  },
);
