import heart from '../../themes/valentine/assets/heart.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './LoveCharades.css';

export const loveCharades = charadesGame(
  {
    id: 'love-charades',
    title: { 'en-US': 'Love Charades', 'pt-PT': 'Mímica do Amor' },
    intro: {
      'en-US':
        'Act out the romantic word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra romântica que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: heart,
    words: {
      'en-US': [
        'Romeo and Juliet',
        'Beauty and the Beast',
        'Cinderella losing her shoe',
        'Sleeping Beauty',
        'The Little Mermaid',
        'Shrek and Fiona',
        'Lady and the Tramp sharing spaghetti',
        'Kissing the frog',
        'Getting down on one knee',
        'Blowing a kiss',
        'Love at first sight',
        'Cupid shooting an arrow',
        'Writing a love letter',
        'Giving a bunch of roses',
        'Serenade under the window',
        'Slow dance',
        'Holding hands',
        'Candlelit dinner',
        'Heart beating fast',
        'Blushing',
        'Box of chocolates',
        'First date nerves',
        'Wedding cake',
        'Throwing the bouquet',
        'Walking down the aisle',
        'Picnic for two',
        'Watching a romantic movie',
        'Making a heart with your hands',
        'Sharing an umbrella',
        'Waiting by the phone',
        'Butterflies in your tummy',
        'Hug',
        'Ice skating together',
        'Rowing a boat on a lake',
        'Secret admirer',
        'Breakfast in bed',
        'Carving initials in a tree',
        'Teddy bear',
        'Wink',
        'Happily ever after',
      ],
      // Portuguese love traditions bring the lenços dos namorados and Santo António's matchmaking.
      'pt-PT': [
        'Romeu e Julieta',
        'A Bela e o Monstro',
        'A Cinderela a perder o sapato',
        'A Bela Adormecida',
        'A Pequena Sereia',
        'O Shrek e a Fiona',
        'A Dama e o Vagabundo a partilhar esparguete',
        'Beijar o sapo',
        'Pôr-se de joelhos para pedir em casamento',
        'Mandar um beijinho',
        'Amor à primeira vista',
        'Cupido a disparar uma seta',
        'Escrever uma carta de amor',
        'Oferecer um ramo de rosas',
        'Serenata à janela',
        'Dança lenta',
        'Dar as mãos',
        'Jantar à luz das velas',
        'Coração a bater depressa',
        'Corar',
        'Caixa de bombons',
        'Nervos do primeiro encontro',
        'Bolo de casamento',
        'Atirar o ramo da noiva',
        'Entrar na igreja',
        'Piquenique a dois',
        'Ver um filme romântico',
        'Fazer um coração com as mãos',
        'Partilhar um guarda-chuva',
        'Esperar pelo telefonema',
        'Borboletas na barriga',
        'Abraço',
        'Patinar de mãos dadas',
        'Passear de barco no lago',
        'Admirador secreto',
        'Pequeno-almoço na cama',
        'Gravar as iniciais numa árvore',
        'Bordar um lenço dos namorados',
        'Piscar o olho',
        'Felizes para sempre',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out famous couples and romantic moments without speaking while the others guess!',
      'pt-PT': 'Faz a mímica de casais famosos e momentos românticos enquanto os outros adivinham!',
    },
    themes: ['valentine'],
    thumbnail,
  },
);
