import santaHat from '../../themes/christmas/assets/santa-hat.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './FestiveCharades.css';

export const festiveCharades = charadesGame(
  {
    id: 'festive-charades',
    title: { 'en-US': 'Festive Charades', 'pt-PT': 'Mímica de Natal' },
    intro: {
      'en-US':
        'Act out the Christmas word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra de Natal que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: santaHat,
    words: {
      'en-US': [
        'Santa coming down the chimney',
        'Reindeer',
        'Building a snowman',
        'Wrapping a present',
        'Decorating the tree',
        'Snowball fight',
        'Ice skating',
        'Elf making toys',
        'Opening presents',
        'Sledding down a hill',
        'Singing carols',
        'Gingerbread man',
        'Hanging a stocking',
        'Eating Christmas dinner',
        'Leaving cookies for Santa',
        'Angel',
        'Nutcracker',
        'Skiing',
        'Penguin',
        'Polar bear',
        'Pulling a cracker',
        'Hot chocolate',
        'Snowflake falling',
        'Christmas lights',
        'Sleigh ride',
        'Writing a letter to Santa',
        'Shaking a present',
        'Star on top of the tree',
        'Candy cane',
        'Jingle bells',
        'Rudolph with a shiny nose',
        'Fireplace',
        'Cold toes',
        'Wearing an ugly sweater',
        'Baking cookies',
        'Snow angel',
        'Toy soldier',
        'Mistletoe',
        'New Year fireworks',
        'Falling asleep after dinner',
      ],
      // Portuguese Christmas has no crackers or candy canes, but it has bolo-rei, the presépio and the 12 raisins.
      'pt-PT': [
        'Pai Natal a descer pela chaminé',
        'Rena',
        'Fazer um boneco de neve',
        'Embrulhar um presente',
        'Enfeitar a árvore',
        'Guerra de bolas de neve',
        'Patinar no gelo',
        'Duende a fazer brinquedos',
        'Abrir os presentes',
        'Descer uma encosta de trenó',
        'Cantar canções de Natal',
        'Boneco de gengibre',
        'Pendurar uma meia',
        'Comer a ceia de Natal',
        'Deixar bolachas ao Pai Natal',
        'Anjo',
        'Quebra-nozes',
        'Esquiar',
        'Pinguim',
        'Urso polar',
        'Comer bolo-rei',
        'Chocolate quente',
        'Floco de neve a cair',
        'Luzes de Natal',
        'Passeio de trenó',
        'Escrever uma carta ao Pai Natal',
        'Abanar um presente',
        'Estrela no topo da árvore',
        'Montar o presépio',
        'Sinos a tocar',
        'Rena de nariz vermelho',
        'Lareira',
        'Pés gelados',
        'Vestir uma camisola de Natal',
        'Fazer bolachas',
        'Anjo na neve',
        'Soldadinho de chumbo',
        'Comer as passas à meia-noite',
        'Fogo de artifício de Ano Novo',
        'Adormecer depois da ceia',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out Christmas words without speaking while the others guess. Reindeer, elves and more!',
      'pt-PT': 'Faz a mímica de palavras de Natal enquanto os outros adivinham. Renas, duendes e muito mais!',
    },
    themes: ['christmas'],
    thumbnail,
  },
);
