import sunglasses from '../../themes/summer/assets/sunglasses.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './SummerCharades.css';

export const summerCharades = charadesGame(
  {
    id: 'summer-charades',
    title: { 'en-US': 'Summer Charades', 'pt-PT': 'Mímica de Verão' },
    intro: {
      'en-US':
        'Act out the summer word on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica da palavra de verão que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: sunglasses,
    words: {
      'en-US': [
        'Surfing a big wave',
        'Building a sandcastle',
        'Sunburn',
        'Putting on sunscreen',
        'Eating an ice cream that melts',
        'Diving into the pool',
        'Cannonball',
        'Crab walking sideways',
        'Walking on hot sand',
        'Blowing up an armband',
        'Snorkeling',
        'Shark fin',
        'Beach volleyball',
        'Fishing',
        'Rowing a boat',
        'Sunbathing',
        'Shaking sand out of a towel',
        'Jellyfish sting',
        'Seagull stealing your sandwich',
        'Water balloon fight',
        'Running into cold water',
        'Burying someone in the sand',
        'Collecting seashells',
        'Flip-flops',
        'Opening a beach umbrella in the wind',
        'Riding a jet ski',
        'Lifeguard',
        'Barbecue',
        'Swatting a mosquito',
        'Camping in a tent',
        'Toasting marshmallows',
        'Sipping from a coconut',
        'Dolphin jumping',
        'Water slide',
        'Packing the car for vacation',
        'Lazy afternoon nap',
        'Floating on an inflatable',
        'Watching the sunset',
        'Getting caught by a wave',
        'Playing with a beach ball',
      ],
      // Portuguese summers have bolas de Berlim on the beach, the arraial and grilled sardines.
      'pt-PT': [
        'Apanhar uma onda de surf',
        'Fazer um castelo de areia',
        'Escaldão',
        'Pôr protetor solar',
        'Comer um gelado que derrete',
        'Mergulhar na piscina',
        'Saltar para a água à bomba',
        'Caranguejo a andar de lado',
        'Andar na areia a escaldar',
        'Encher umas braçadeiras',
        'Mergulhar com snorkel',
        'Barbatana de tubarão',
        'Vólei de praia',
        'Pescar',
        'Remar um barco',
        'Apanhar sol',
        'Sacudir a areia da toalha',
        'Picadela de alforreca',
        'Gaivota a roubar a sandes',
        'Guerra de balões de água',
        'Entrar na água fria',
        'Enterrar alguém na areia',
        'Apanhar conchas',
        'Chinelos',
        'Abrir o chapéu de sol com vento',
        'Andar de mota de água',
        'Nadador-salvador',
        'Comer uma bola de Berlim',
        'Matar um mosquito',
        'Acampar numa tenda',
        'Assar sardinhas',
        'Beber de um coco',
        'Golfinho aos saltos',
        'Escorrega aquático',
        'Arrumar o carro para as férias',
        'Sesta depois do almoço',
        'Boiar numa boia',
        'Ver o pôr do sol',
        'Ser apanhado por uma onda',
        'Dançar no arraial',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out summer things without speaking while the others guess. Surfing, sunburn and more!',
      'pt-PT': 'Faz a mímica de coisas de verão enquanto os outros adivinham. Surf, escaldões e muito mais!',
    },
    themes: ['summer'],
    thumbnail,
  },
);
