import mask from '../../themes/carnival/assets/mask.svg';
import { charadesGame } from '../charades/game';
import thumbnail from './assets/thumbnail.jpg';
import './CostumeCharades.css';

export const costumeCharades = charadesGame(
  {
    id: 'costume-charades',
    title: { 'en-US': 'Costume Charades', 'pt-PT': 'Mímica de Disfarces' },
    intro: {
      'en-US':
        'Act out the costume or carnival character on the screen without saying a word, while everyone else shouts their guesses. Every word they get earns you points. Stuck? Skip it!',
      'pt-PT':
        'Faz a mímica do disfarce ou da personagem de carnaval que aparece no ecrã sem dizer nada, enquanto os outros gritam palpites. Cada palavra que adivinharem dá-te pontos. Encravaste? Salta!',
    },
    icon: mask,
    words: {
      'en-US': [
        'Pirate',
        'Superhero',
        'Astronaut',
        'Cowboy',
        'Princess',
        'Robot',
        'Ninja',
        'Firefighter',
        'Doctor',
        'Chef',
        'Clown juggling',
        'Mime stuck in a box',
        'Samba dancer',
        'Stilt walker',
        'Fire breather',
        'Magician',
        'Tightrope walker',
        'Lion tamer',
        'Police officer',
        'Mermaid',
        'Fairy',
        'Wizard',
        'Knight on a horse',
        'King on his throne',
        'Penguin',
        'Dinosaur',
        'Butterfly',
        'Bee',
        'Cat',
        'Ballerina',
        'Rock star',
        'Mummy',
        'Scarecrow',
        'Pharaoh',
        'Viking',
        'Surfer',
        'Throwing streamers',
        'Dancing in the parade',
        'Playing the big drum',
        'Putting on face paint',
      ],
      // Portuguese carnival brings the caretos of Podence and the Torres Vedras matrafonas.
      'pt-PT': [
        'Pirata',
        'Super-herói',
        'Astronauta',
        'Cowboy',
        'Princesa',
        'Robô',
        'Ninja',
        'Bombeiro',
        'Médico',
        'Cozinheiro',
        'Palhaço a fazer malabarismo',
        'Mimo preso numa caixa',
        'Bailarina de samba',
        'Homem das andas',
        'Cuspidor de fogo',
        'Mágico',
        'Equilibrista na corda bamba',
        'Domador de leões',
        'Polícia',
        'Sereia',
        'Fada',
        'Feiticeiro',
        'Cavaleiro a cavalo',
        'Rei no trono',
        'Pinguim',
        'Dinossauro',
        'Borboleta',
        'Abelha',
        'Gato',
        'Bailarina',
        'Estrela de rock',
        'Múmia',
        'Espantalho',
        'Faraó',
        'Viking',
        'Surfista',
        'Atirar serpentinas',
        'Careto a chocalhar',
        'Tocar o bombo',
        'Pintar a cara',
      ],
    },
  },
  {
    enabled: true,
    description: {
      'en-US': 'Act out costumes and carnival characters without speaking while the others guess!',
      'pt-PT': 'Faz a mímica de disfarces e personagens de carnaval enquanto os outros adivinham!',
    },
    themes: ['carnival'],
    thumbnail,
  },
);
